site_name: SII et Informatique - Lycée La Martinière Monplaisir - Lyon
site_url: https://xpessoles.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mode sombre
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Mode clair
      primary: teal
      accent: lime
  icon:
    tag:
      TEST_TAG: simple/python
        

plugins:
  - social
  - search
  - tags:
      tags_file: tags.md
      test_tag: TEST_TAG
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xpessoles
#    - icon: fontawesome/brands/twitter
      #link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xavier-pessoles-29061968/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/xpessoles"  target="_blank" rel="noopener">Xavier Pessoles</a>


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Acceuil: 'index.md'
- PSI:
    - '2023-2024' : 'PSI/2023_2024.md'
    - 'Modélisation des SLCI': 'PSI/Cycle_01.md'
    - 'Performance des SLCI': 'PSI/Cycle_02.md'
    - 'Correction des SLCI': 'PSI/Cycle_03.md'
    - 'Théorie des mécanismes': 'PSI/Cycle_04.md'
    - 'Dynamique': 'PSI/Cycle_05.md'
    - 'Energétique': 'PSI/Cycle_06.md'
- Révisions:
    - 'Cinématique': 'Revisions/01_Cinematique'
    - 'Statique': 'Revisions/02_Statique'
- Informatique:
    - 'Cycle 1': 'Informatique/Cycle_01.md'
    - 'Cycle 2': 'Informatique/Cycle_02.md'
- Labo SII : 
    - 'Accueil': 'Labo_SII/index.md'
- Divers : 
    - 'Ce site': 'Divers/index.md'
