site_name: SII et Informatique - Lycée La Martinière Monplaisir - Lyon
site_url: https://xpessoles.github.io/
repo_url: https://github.com/xpessoles/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking # Menu de la page à droite ?
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips  # pour les infobulles sur les mots ?
  icon: 
    logo: bootstrap/logo-capytale
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mode sombre
      primary: teal
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Mode clair
      primary: teal
      accent: teal
  icon:
    logo: material/robot-industrial-outline
    tag:
      html: octicons/gear-16
      TESTTAG: simple/python
      a308: octicons/gear-16

plugins:
  - social
  - search
  - tags:  
      tags_file: Divers/tags.md
  #- glightbox Marche pas
  #- mkdocs-jupyter # CA MARCHE PAS
  
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xpessoles
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xavier-pessoles-29061968/
  tags:
      Compatibility: compat  
      test_tag: TESTTAG
      A3-08: a308
      HTML5: html
      SLCI: slci
      CIN: cin
      STAT: stat
      CHS: chs
  analytics:
    provider: google
    property: G-45JVSEKHDF

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets   # pour les infobulles sur les mots ?
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list           # pour les infobulles sur les mots ?
  - abbr                # pour les infobulles sur les mots ?
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:  # Ajouter de nouveaux icones
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  
copyright: |
  &copy; 2025 <a href="https://github.com/xpessoles"  target="_blank" rel="noopener">Xavier Pessoles</a>


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Accueil: 
    - index.md
    - Merci: Divers/merci.md
    - Sites: Divers/sites.md
    - Contact: Divers/contact.md
- PSI:
    - PSI/index.md
    - Documents 2024-2025: PSI/2024_2025.md
    - Documents 2023-2024: PSI/2023_2024.md
    - Modélisation des SLCI: 
      - Transformée de Laplace: PSI/slci/slci-laplace.md
      - Modélisation par schéma-blocs: PSI/slci/slci-blocs.md
#      - Systèmes d'ordre 1 et 2:  PSI/slci/slci-ordre12.md
      - Analyse fréquentielle: PSI/slci/slci-bode.md
      - Synthèse: PSI/slci/slci-synthese.md
    - Performances des SLCI: 
      #- PSI/slci/slci-perf.md
      - Stablité des systèmes: PSI/slci/slci-stabilite.md
      - Précision des systèmes: PSI/slci/slci-precision.md
      - Rapidité des systèmes: PSI/slci/slci-rapidite.md
      - Révisions: PSI/slci/slci-revisions.md
    - Modélisation polyphysique: PSI/slci/slci-multiphy.md
    - Correction des SLCI:
      #- PSI/cor/index.md
      - Correcteur proportionnel: PSI/slci/slci-p.md
      - Correcteur proportionnel intégral: PSI/slci/slci-pi.md
      - Correcteur à avance de phase: PSI/slci/slci-ap.md
      - Correcteur à retard de phase: PSI/slci/slci-rp.md
      - Correcteur: PSI/slci/slci-correcteur.md
      - Correcteurs: PSI/slci/slci-correcteurs.md
      - Commande des systèmes: PSI/slci/slci-commande.md
    - Théorie des mécanismes:
      - PSI/chs/index.md
      - Liaisons équivalentes: PSI/chs/chs-leq.md
      - Théorie des mécanismes: PSI/chs/chs-hs.md
      - PSI/chs/chs-.md
    - Dynamique: 
      #- PSI/dyn/index.md
      - Caractéristiques inertielles: PSI/dyn/dyn-inertie.md
      - Cinétique: PSI/dyn/dyn-cin.md
      - PFD - Mouvements 1d: PSI/dyn/dyn-1d.md
      - PFD: PSI/dyn/dyn-pfd.md
      - PFD - Chaînes ouvertes: PSI/dyn/dyn-pfd-co.md
      - PFD - Chaînes fermées: PSI/dyn/dyn-pfd-cf.md
      - PFD - Véhicules: PSI/dyn/dyn-pfd-vehicule.md
      - PSI/dyn/dyn-.md
    - Energétique:
      #- PSI/tec/index.md
      #- Cours: PSI/tec/tec-cours.md
      - Inertie équivalente: PSI/tec/tec-jeq.md
      - TEC Mouvements simples: PSI/tec/tec-1d.md
      - TEC Mouvements complexes: PSI/tec/tec-3d.md
      - TEC Véhicules: PSI/tec/tec-vehicule.md
      - PSI/tec/tec-.md
    #- Résolution numérique:
      #- PSI/num/index.md
      #- Méthodes numériques : PSI/num/num-mn.md
      #- Introduction IA : PSI/num/num-ia.md
      #- Introduction RN : PSI/num/num-rn.md
- MP:
    - MP/index.md
    - Documents 2024-2025: MP/2024_2025.md
- Oraux :
    - Oraux/index.md
    - Oraux/TPs.md
    - Oraux/activites.md
    - Oraux/logiciels.md
    - Oraux/mines-telecom.md
- Révisions Sup:
    - Revisions/index.md
    - Cinématique: 
      - Revisions/cin/index.md
      - Géométrie: Revisions/cin/cin-geo.md
      - Modélisation: Revisions/cin/cin-mod.md
      - Résolution cinématique: Revisions/cin/cin-va.md
      - Cinématique du point: Revisions/cin/cin-point.md
    - Statique: 
      - Revisions/stat/index.md
      - Modélisation des AM: Revisions/stat/stat-mam.md
      - Frottement sec: Revisions/stat/stat-frot.md
      - Résolution du PFS 2D: Revisions/stat/stat-pfs-2d.md
      - Résolution du PFS 3D: Revisions/stat/stat-pfs-3d.md
- Labo SII: 
    - Labo_SII/index.md 
    - BGR-300 : Labo_SII/bgr-300.md
    - Bras BETA : Labo_SII/bras-beta.md
    - Cheville NAO : Labo_SII/cheville-nao.md
    - CoMAX : Labo_SII/comax.md
    - ControlX : Labo_SII/controlx.md
    - Cordeuse : Labo_SII/cordeuse.md
    - Direction Assistée Electrique : Labo_SII/dae.md
    - D2C : Labo_SII/d2c.md
    - Ericc 3 : Labo_SII/ericc.md
    - Evolap : Labo_SII/evolap.md
    - MaxPID : Labo_SII/maxpid.md
    - Moteur à courant continu : Labo_SII/moteurcc.md
    - Moby Crea : Labo_SII/moby-crea.md
    - Pilote Automatique de Voilier : Labo_SII/pilote-auto.md
    - Portail ABB : Labo_SII/portail.md
    - Robot à câbles RC4 : Labo_SII/rc4.md
    - Robot Delta 2D : Labo_SII/robot-delta.md
    - Robot Haptique : Labo_SII/robot-haptique.md
    - Barrière Symapct : Labo_SII/sympact.md
    - Toit de 206 cc : Labo_SII/toit-206.md
    - Tourelle 2 axes : Labo_SII/tourelle.md
    - Imprimante 3D : Labo_SII/i3d.md
    - Plateforme 6 axes : Labo_SII/plateforme.md
    - Arduino : Labo_SII/arduino.md
    - Solidworks : Labo_SII/sw.md
    - Matlab Simulink : Labo_SII/matlab.md
- Activités SII: 
    - activites/index.md 
    - SYS-01 : activites/SYS-01.md
    - GEO-01 : activites/GEO-01.md
    - GEO-03 : activites/GEO-03.md
    - CIN-01 : activites/CIN-01.md
    - CIN-02 : activites/CIN-02.md
    - CIN-03 : activites/CIN-03.md
    - STAT-02 : activites/STAT-02.md
    - STAT-03 : activites/STAT-03.md
    - CHS-03 : activites/CHS-03.md
    - DYN-01 : activites/DYN-01.md
    - DYN-03 : activites/DYN-03.md
    - DYN-04 : activites/DYN-04.md
    - DYN-05 : activites/DYN-05.md
    - DYN-06 : activites/DYN-06.md
    - TEC-05 : activites/TEC-05.md
    - SLCI : activites/SLCI.md
    - SLCI-02 : activites/SLCI-02.md
    - SLCI-03 : activites/SLCI-03.md
    - SLCI-07 : activites/SLCI-07.md
    - SLCI-11 : activites/SLCI-11.md
    - PERF-02 : activites/PERF-02.md
    - PERF-05 : activites/PERF-05.md
    - PERF-06 : activites/PERF-06.md
    - COR-02 : activites/COR-02.md
    - COR-03 : activites/COR-03.md
    - COR-04 : activites/COR-04.md
    - SEQ-03 : activites/SEQ-03.md
    - RDM-01 : activites/RDM-01.md
    - RDM-05 : activites/RDM-05.md
    - ELEC-01 : activites/ELEC-01.md
    - ELEC-04 : activites/ELEC-04.md
    - ELEC-05 : activites/ELEC-05.md
    - PPM-01 : activites/PPM-01.md
    - PPM-02 : activites/PPM-02.md
- PTSI-PT :
  - old-ptsi/index.md
  - Plans: old-ptsi/plans.md
  - Oldies : old-ptsi/old_ptsi.md
- Informatique:
  - Informatique/index.md
  - 2023-2024: Informatique/2023-2024.md
- Notebooks: Informatique/notebooks.md
- TIPE:
  - tipe/index.md
  - Courbes Python : 
    - Courbes : tipe/courbes.md
    - Import données : tipe/import.md
    - Regression linéaire : tipe/regression.md
    - Polyfit : tipe/polyfit.md
    - Incertitudes : tipe/incertitudes.md
    - Diagrammes log : tipe/log.md
    - Figures multiples : tipe/multiples.md
  - Logiciels : tipe/logiciels.md
- Evaluation:
  - evaluation/index.md
- Divers : 
    - Index: Divers/tags.md
    - Jupyter: Divers/archive/test.ipynb
    - Bac à sable: Divers/index.md
    - Carte: Divers/map.md
- Rugby :
    - Rugby/index.md
    - Echauffement : Rugby/echauffement.md
    - Jeu en mouvement : Rugby/mouvement.md
        - Utilisation de l'espace : Rugby/espace.md
        - Utilisation du partenaire : Rugby/partenaire.md
        - Soutien du porteur de balle : Rugby/soutien.md
        - Organisation défensive : Rugby/defense.md
    - Gestion des contacts et des luttes : Rugby/contact.md
        
    