site_name: SII et Informatique - Lycée La Martinière Monplaisir - Lyon
site_url: https://xpessoles.github.io/
repo_url: https://github.com/xpessoles/xpessoles.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking # Menu de la page à droite ?
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips  # pour les infobulles sur les mots ?
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mode sombre
      primary: teal
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Mode clair
      primary: teal
      accent: teal
  icon:
    logo: material/robot-industrial-outline
    tag:
      html: octicons/gear-16
      TESTTAG: simple/python
      a308: octicons/gear-16

plugins:
  - social
  - search
  - tags:  
      tags_file: Divers/tags.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xpessoles
#    - icon: fontawesome/brands/twitter
      #link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xavier-pessoles-29061968/
  tags:
      Compatibility: compat  
      test_tag: TESTTAG
      A3-08: a308
      HTML5: html
      SLCI: slci
      CIN: cin
      STAT: stat
      CHS: chs
  analytics:
    provider: google
    property: G-45JVSEKHDF

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets   # pour les infobulles sur les mots ?
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list           # pour les infobulles sur les mots ?
  - abbr                # pour les infobulles sur les mots ?
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  
copyright: |
  &copy; 2024 <a href="https://github.com/xpessoles"  target="_blank" rel="noopener">Xavier Pessoles</a>


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Acceuil: index.md
- PSI:
    - PSI/index.md
    - Documents 2023-2024: PSI/2023_2024.md
    - Modélisation des SLCI: 
      - Transformée de Laplace: PSI/slci/slci-laplace.md
      - Modélisation par schéma-blocs: PSI/slci/slci-blocs.md
#      - Systèmes d'ordre 1 et 2:  PSI/slci/slci-ordre12.md
      - Analyse fréquentielle: PSI/slci/slci-bode.md
      - Synthèse: PSI/slci/slci-synthese.md
    - Performances des SLCI: 
      #- PSI/slci/slci-perf.md
      - Stablité des systèmes: PSI/slci/slci-stabilite.md
      - Précision des systèmes: PSI/slci/slci-precision.md
      - Rapidité des systèmes: PSI/slci/slci-rapidite.md
      - Révisions: PSI/slci/slci-revisions.md
    - Modélisation polyphysique: PSI/slci/slci-multiphy.md
    - Correction des SLCI:
      #- PSI/cor/index.md
      - Correcteur proportionnel: PSI/slci/slci-p.md
      - Correcteur proportionnel intégral: PSI/slci/slci-pi.md
      - Correcteur à avance de phase: PSI/slci/slci-ap.md
      - Correcteur à retard de phase: PSI/slci/slci-rp.md
      - Correcteur: PSI/slci/slci-correcteur.md
      - Correcteurs: PSI/slci/slci-correcteurs.md
      - Commande des systèmes: PSI/slci/slci-commande.md
    - Théorie des mécanismes:
      #- PSI/chs/index.md
      - Liaisons équivalentes: PSI/chs/chs-leq.md
      - Théorie des mécanismes: PSI/chs/chs-hs.md
    - Dynamique: 
      #- PSI/dyn/index.md
      - Caractéristiques inertielles: PSI/dyn/dyn-inertie.md
      - Cinétique: PSI/dyn/dyn-cin.md
      - PFD - Mouvements 1d: PSI/dyn/dyn-1d.md
      - PFD: PSI/dyn/dyn-pfd.md
      - PFD - Chaînes ouvertes: PSI/dyn/dyn-pfd-co.md
      - PFD - Chaînes fermées: PSI/dyn/dyn-pfd-cf.md
      - PFD - Véhicules: PSI/dyn/dyn-pfd-vehicule.md
    - Energétique:
      #- PSI/tec/index.md
      - Cours: PSI/tec/tec-cours.md
      - Inertie équivalente: PSI/tec/tec-jeq.md
      - TEC Mouvements simples: PSI/tec/tec-1d.md
      - TEC Mouvements complexes: PSI/tec/tec-3d.md
      - TEC Véhicules: PSI/tec/tec-vehicule.md
    - Résolution numérique:
      #- PSI/num/index.md
      - Méthodes numériques : PSI/num/num-mn.md
      - Introduction IA : PSI/num/num-ia.md
      - Introduction RN : PSI/num/num-rn.md
- Révisions:
    - Revisions/index.md
    - Cinématique: 
      - Revisions/cin/index.md
      - Géométrie: Revisions/cin/cin-geo.md
      - Modélisation: Revisions/cin/cin-mod.md
      - Résolution cinématique: Revisions/cin/cin-va.md
      - Cinématique du point: Revisions/cin/cin-point.md
    - Statique: 
      - Revisions/stat/index.md
      - Modélisation des AM: Revisions/stat/stat-mam.md
      - Frottement sec: Revisions/stat/stat-frot.md
      - Résolution du PFS 2D: Revisions/stat/stat-pfs-2d.md
      - Résolution du PFS 3D: Revisions/stat/stat-pfs-3d.md
- Informatique:
    - Informatique/index.md
    - 2023-2024: Informatique/2023-2024.md
- Labo SII : 
    - Labo_SII/index.md
    - BGR-300 : Labo_SII/bgr-300.md
- Divers : 
    - Carte: Divers/map.md
    - Ce site: Divers/index.md
    - Index: Divers/tags.md
    - Python Markdown: Divers/python-markdown.md

